apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 2100
        - containerPort: 2101
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: ftps1
    port: 21
    targetPort: 21
  - name: ftps2
    port: 2100
    targetPort: 2100
  - name: ftps3
    port: 2101
    targetPort: 2101