apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      restartPolicy: Always
      containers:
      - name: influxdb
        image: influxdb
        imagePullPolicy: Never
        ports:
          - containerPort: 8086
        livenessProbe:
          exec:
            command:
            - sh
            - healthy.sh
          initialDelaySeconds: 30
          periodSeconds: 5
        volumeMounts:
          - mountPath: "/root/.influxdb"
            name: influxdb
      volumes:
        - name: influxdb
          persistentVolumeClaim:
            claimName: influxdb
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  selector:
    app: influxdb
  ports:
  - port: 8086
    targetPort: 8086
